[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = '10.0.0.8'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'TB IoT Export Service'
Timeout = '5s'

[Registry]
Host = '10.0.0.100'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = '10.0.0.100'
  Port = 48080
  [Clients.Logging]
  Protocol = "http"
  Host = "10.0.0.100"
  Port = 48061

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = '10.0.0.100'
        Port = 5563
        Protocol = 'tcp'

[Logging]
EnableRemote = false
File = ''

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic=""

[ApplicationSettings]
tbIOTMQTTProtocol   = "tcp"
tbIOTMQTTHost       = "10.0.0.200"
tbIOTMQTTPort       = "1883"
TBIoTMQTTUserName   = "rftT5DEba9bm2Dm6TFb4"
topic               = "v1/devices/me/telemetry"
tbIOTThingName      = "testThing"
MQTTCert            = "./certs/user.client.crt"
MQTTKey             = "./certs/user.client.key"
SkipCertVerify	    = "false"
PersistOnError	    = "false"
TbDeviceNames       = ""

